/// Flutter icons GoogleIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GoogleIcon
///      fonts:
///       - asset: fonts/GoogleIcon.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class GoogleIcon {
  GoogleIcon._();

  static const _kFontFam = 'GoogleIcon';
  static const String? _kFontPkg = null;

  static const IconData bear_trap = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
